# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171110_1020'),
        ('post', '0002_newsfeed_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('like', models.IntegerField(default=0)),
                ('unlikes', models.IntegerField(default=0)),
                ('commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.NewsFeed')),
            ],
        ),
    ]
