# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_newsvalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsValues',
            new_name='NewsValue',
        ),
    ]
