# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171110_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsvalue',
            old_name='value',
            new_name='feedname',
        ),
    ]
