# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20171110_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvalue',
            name='comm_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
