# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_newsvalue_comm_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['-pub_date']},
        ),
    ]
