# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20171113_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsvalue',
            options={'ordering': ['-comm_date']},
        ),
    ]
