# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_remove_newsfeed_feedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsvalue',
            name='like',
        ),
        migrations.RemoveField(
            model_name='newsvalue',
            name='unlikes',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
