# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20171116_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='feedpic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
