# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171108_0403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
