# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dob',
        ),
    ]
