# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171114_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
