# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171114_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
